### ISSUE TITLE
Never sleep screen?

### ISSUE THREAD

**Issue by Adeptus-Astartes** [picoxr/AndroidHelper#1]
Hi, 
is that possible to set never sleep mode? like it has done in unity
![image](https://user-images.githubusercontent.com/70582099/97163424-4cb7bb80-1789-11eb-8e58-f8f35df6baaf.png)
So -1 instead 999999 for example.
In an addition, this function should be safer, since this is system-wide settings. 
Also, I want to see here option to get screen timeout, so I would not overwrite user settings

**Comment by picoxr** [comment]
You can pass "-1" for setting never sleep. And the wiki page has been updated. Thanks for your feedback.
