### ISSUE TITLE
GetFreeStorage should return long instead float

### ISSUE THREAD

**Issue by Adeptus-Astartes** [picoxr/AndroidHelper#2]

**Comment by picoxr** [comment]
Thanks for your feedback. For now, this function return value is in GB, that is why we use float instead of long.

**Comment by Adeptus-Astartes** [comment]
I suggest you to update function to 
` var jc = new AndroidJavaClass("android.os.Environment");
        var file = jc.CallStatic<AndroidJavaObject>("getDataDirectory");
        var path = file.Call<string>("getAbsolutePath");

        var stat = new AndroidJavaObject("android.os.StatFs", path);
        var blocks = stat.Call<long>("getAvailableBlocksLong");
        var blockSize = stat.Call<long>("getBlockSizeLong");

        var space = blocks * blockSize;`

**Comment by picoxr** [comment]
The API you suggest is more accurate, thanks, I'll update it later.
