### ISSUE TITLE
SilentInstall does not work. Package com.xxx does not belong to 1000

### ISSUE THREAD

**Issue by Uppanen** [picoxr/AndroidHelper#5]
I've tried to implement the deviceHelper.silentInstall-command on my own app and had an error message. So I downloaded the example project and changed the apk-file used in the silentInstall-command. The application does not install and the following error message is shown:

/com.picovr.example D/DeviceHelper: silentInstall: apkPath: /sdcard/Download/xxx.apk, installerPkgName: com.xxx
/com.picovr.example D/SilentInstaller: install: apkPath: /sdcard/Download/xxx.apk, installPkgName: xxx.picogamelauncher
/com.picovr.example E/DeviceHelper: onError: Error: java.lang.SecurityException: Package xxx.picogamelauncher does not belong to 1000

I changed the original application name and replaced it with "xxx" in the log text above.
I can use the silentUninstall command succesfully but the silentInstall does not work.

**Comment by picoxr** [comment]
The ``packagename`` parameter should be the package name of your current application, not the package name of the application being installed. In example project, remain "com.picovr.example".
You can refer to the API description: https://github.com/picoxr/AndroidHelper/wiki/DeviceHelper#void-silentinstallstring-apkpath-string-packagename-.

**Comment by Uppanen** [comment]
Yup, that was it. Thank youuuu.
